server:
  port: 8081

spring:
  r2dbc:
    url: ${DATABASE_URL:r2dbc:postgresql://localhost:15432/oauthdb}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}

jwt:
  secretKey: 8n3MrjYcZkADRLPmj6BZnFTLmAhCrcga6sD9eCASXABT5fp3Xe
  accessTokenExpirationHour: 1
  refreshTokenExpirationHour: 720

naver:
  oauthHost: https://nid.naver.com
  profileHost: https://openapi.naver.com
  tokenUrl: /oauth2.0/token
  profileUrl: /v1/nid/me
  clientId:
  clientSecret:
  state:

kakao:
  oauthHost: https://kauth.kakao.com
  profileHost: https://kapi.kakao.com
  tokenUrl: /oauth/token
  profileUrl: /v2/user/me
  clientId:
  redirectUri: http://localhost:8080/login/kakao

google:
  oauthHost: https://oauth2.googleapis.com
  profileHost: https://www.googleapis.com
  tokenUrl: /token
  profileUrl: /userinfo/v2/me
  clientId:
  clientSecret:
  redirectUri: http://localhost:8080/login/google
