services:
  oauth-database:
    image: postgres:16
    container_name: oauth-database
    environment:
      POSTGRES_DB: "oauthdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
  oauth-backend:
    build:
      context: .
    environment:
      - DATABASE_URL=r2dbc:postgresql://oauth-database:5432/oauthdb
    container_name: oauth-backend
    restart: always
    depends_on:
      - oauth-database
    ports:
      - "8081:8081"
