services:
  database:
    image: postgres:16
    container_name: oauth-database
    environment:
      POSTGRES_DB: "oauthdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "15432:5432"